### PR TITLE
Declare support for Dart 2.0 stable

### PR DESCRIPTION
**Pull request by mit-mit**
Now that Dart 2.0 has launched, would be great to declare 2.0 support for this popular package

### CODE REVIEW

**Comment by mit-mit** [comment]
cc rxlabz

**Comment by emostar** [comment]
I went ahead and forked this project and added this PR (with the fix to pull gradle down) and it is available at https://github.com/emostar/audioplayer and published at https://pub.dartlang.org/packages/audioplayer2

**Comment by tmcalves** [comment]
@emostar tried your forks code and got the error running for iOS

> Running pod install...
> CocoaPods' output:
> ↳
>       Preparing
>     
>     Analyzing dependencies
>     
>     Inspecting targets to integrate
>       Using `ARCHS` setting to build architectures of target `Pods-Runner`: (``)
>     
>     Finding Podfile changes
>       A audioplayer2
>       - Flutter
>       - shared_preferences
>       - url_launcher
>     
>     Fetching external sources
>     -> Fetching podspec for `Flutter` from `.symlinks/flutter/ios`
>     -> Fetching podspec for `audioplayer2` from `.symlinks/plugins/audioplayer2/ios`
>     [!] No podspec found for `audioplayer2` in `.symlinks/plugins/audioplayer2/ios`
>     
>     /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/external_sources/path_source.rb:14:in `block in fetch'
>     /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:85:in `titled_section'
>     /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/external_sources/path_source.rb:11:in `fetch'
>     /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:697:in `fetch_external_source'
>     /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:673:in `block (2 levels) in fetch_external_sources'
>     /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:672:in `each'
>     /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:672:in `block in fetch_external_sources'
>     /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
>     /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:671:in `fetch_external_sources'
>     /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer/analyzer.rb:85:in `analyze'
>     /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:243:in `analyze'
>     /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:154:in `block in resolve_dependencies'
>     /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
>     /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:153:in `resolve_dependencies'
>     /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:116:in `install!'
>     /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
>     /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
>     /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
>     /usr/local/Cellar/cocoapods/1.5.3/libexec/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
>     /usr/local/Cellar/cocoapods/1.5.3/libexec/bin/pod:22:in `load'
>     /usr/local/Cellar/cocoapods/1.5.3/libexec/bin/pod:22:in `<main>'
> Error output from CocoaPods:
> ↳
>     
>     [!] Automatically assigning platform `ios` with version `8.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
> Error running pod install
> Error launching application on iPhone X.
> 
> Any idea what can be wrong there?

**Comment by emostar** [comment]
@tmcalves It should be fixed in v0.5.2, please try again!

**Comment by mit-mit** [comment]
Closing, looks like this happened in https://github.com/rxlabz/audioplayer/commit/7faa7854b15bd080378dcedefcdb0dc8f6f6389c#diff-fb2d52cd953afedcafc9fe7629c6f132

**Pull request closed without merging**
